/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Cajas.Aviso;
import Clases.Factorial;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Calculadora extends javax.swing.JFrame {
        double a,b;
        String Numero="",c;
        char op;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon image= new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen2.png"));
        setIconImage(image.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttnFactorial = new javax.swing.JButton();
        bttnPunto = new javax.swing.JButton();
        bttnNumero6 = new javax.swing.JButton();
        bttnResultado = new javax.swing.JButton();
        bttnNumero3 = new javax.swing.JButton();
        bttnClear = new javax.swing.JButton();
        bttnNumero2 = new javax.swing.JButton();
        txtValores = new javax.swing.JTextField();
        bttnNumero1 = new javax.swing.JButton();
        bttnResta = new javax.swing.JButton();
        bttnDivision = new javax.swing.JButton();
        bttnNumero4 = new javax.swing.JButton();
        bttnMultiplicacion = new javax.swing.JButton();
        bttnNumero5 = new javax.swing.JButton();
        bttnSuma = new javax.swing.JButton();
        bttnNumero8 = new javax.swing.JButton();
        bttnNumero9 = new javax.swing.JButton();
        bttnNumero0 = new javax.swing.JButton();
        bttnNumero7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora");

        bttnFactorial.setText("n!");
        bttnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnFactorialActionPerformed(evt);
            }
        });

        bttnPunto.setText(".");
        bttnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPuntoActionPerformed(evt);
            }
        });

        bttnNumero6.setText("6");
        bttnNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero6ActionPerformed(evt);
            }
        });

        bttnResultado.setText("=");
        bttnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnResultadoActionPerformed(evt);
            }
        });

        bttnNumero3.setText("3");
        bttnNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero3ActionPerformed(evt);
            }
        });

        bttnClear.setText("C");
        bttnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnClearActionPerformed(evt);
            }
        });

        bttnNumero2.setText("2");
        bttnNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero2ActionPerformed(evt);
            }
        });

        txtValores.setText("0");
        txtValores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValoresKeyTyped(evt);
            }
        });

        bttnNumero1.setText("1");
        bttnNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero1ActionPerformed(evt);
            }
        });

        bttnResta.setText("-");
        bttnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRestaActionPerformed(evt);
            }
        });

        bttnDivision.setText("/");
        bttnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDivisionActionPerformed(evt);
            }
        });

        bttnNumero4.setText("4");
        bttnNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero4ActionPerformed(evt);
            }
        });

        bttnMultiplicacion.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bttnMultiplicacion.setText("*");
        bttnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnMultiplicacionActionPerformed(evt);
            }
        });

        bttnNumero5.setText("5");
        bttnNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero5ActionPerformed(evt);
            }
        });

        bttnSuma.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bttnSuma.setText("+");
        bttnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSumaActionPerformed(evt);
            }
        });

        bttnNumero8.setText("8");
        bttnNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero8ActionPerformed(evt);
            }
        });

        bttnNumero9.setText("9");
        bttnNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero9ActionPerformed(evt);
            }
        });

        bttnNumero0.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bttnNumero0.setText("0");
        bttnNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero0ActionPerformed(evt);
            }
        });

        bttnNumero7.setText("7");
        bttnNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNumero7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValores, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttnNumero4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttnNumero5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttnNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttnNumero1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttnNumero2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttnNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bttnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bttnNumero7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttnNumero8)
                                    .addComponent(bttnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttnNumero9)
                                    .addComponent(bttnDivision))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bttnPunto, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addComponent(bttnNumero0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bttnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bttnResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bttnFactorial))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(bttnClear)
                        .addGap(5, 5, 5)
                        .addComponent(bttnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bttnNumero8)
                                    .addComponent(bttnNumero9)
                                    .addComponent(bttnNumero7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bttnNumero4)
                                    .addComponent(bttnNumero5)
                                    .addComponent(bttnNumero6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttnSuma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bttnDivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bttnResta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bttnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttnNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnNumero1)
                            .addComponent(bttnNumero2)
                            .addComponent(bttnNumero3)
                            .addComponent(bttnPunto)
                            .addComponent(bttnFactorial))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnFactorialActionPerformed
       double num= Double.parseDouble(txtValores.getText());
        txtValores.setText(""+Factorial.getAcumulado(num));
    }//GEN-LAST:event_bttnFactorialActionPerformed

    private void bttnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPuntoActionPerformed
        Numero=Numero+".";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnPuntoActionPerformed

    private void bttnNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero6ActionPerformed
        Numero=Numero+"6";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero6ActionPerformed

    private void bttnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnResultadoActionPerformed

        double r=0;
        b=Double.parseDouble(txtValores.getText());

        switch(op){
            case '-' : r=a-b;
            break;
            case '+' : r=a+b;
            break;
            case '/' :
            if(b==0){

                while(b==0){
                    Aviso.mostrar("Recuerde que las divisiones entre 0 no están permitidas");
                    c = JOptionPane.showInputDialog(this,"Ingresa un numero diferente de 0");
                    b=Double.parseDouble(c);
                }
                r=a/b;
            }else{
                r=a/b;
            }
            break;
            case '*' : r=a*b;
            break;
        }
        txtValores.setText(""+r);
        Numero="";
    }//GEN-LAST:event_bttnResultadoActionPerformed

    private void bttnNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero3ActionPerformed
        Numero=Numero+"3";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero3ActionPerformed

    private void bttnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnClearActionPerformed
        txtValores.setText("0");
        a=0;
        b=0;
        Numero="";
        txtValores.requestFocus();
    }//GEN-LAST:event_bttnClearActionPerformed

    private void bttnNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero2ActionPerformed
        Numero=Numero+"2";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero2ActionPerformed

    private void txtValoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValoresKeyTyped
        char c= evt.getKeyChar();

        if(c<'0'|| c>'9') evt.consume();

        char Tecla=evt.getKeyChar();

        if(Tecla==KeyEvent.VK_ENTER){

            bttnResultado.doClick();
        }

    }//GEN-LAST:event_txtValoresKeyTyped

    private void bttnNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero1ActionPerformed
        Numero=Numero+"1";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero1ActionPerformed

    private void bttnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRestaActionPerformed
        op='-';
        a=Double.parseDouble(txtValores.getText());
        txtValores.setText("");
        Numero="";
        txtValores.requestFocus();
    }//GEN-LAST:event_bttnRestaActionPerformed

    private void bttnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDivisionActionPerformed
        op='/';

        a=Double.parseDouble(txtValores.getText());

        txtValores.setText("");
        Numero="";
        txtValores.requestFocus();

    }//GEN-LAST:event_bttnDivisionActionPerformed

    private void bttnNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero4ActionPerformed
        Numero=Numero+"4";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero4ActionPerformed

    private void bttnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnMultiplicacionActionPerformed
        op='*';
        a=Double.parseDouble(txtValores.getText());
        txtValores.setText("");
        Numero="";
        txtValores.requestFocus();
    }//GEN-LAST:event_bttnMultiplicacionActionPerformed

    private void bttnNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero5ActionPerformed
        Numero=Numero+"5";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero5ActionPerformed

    private void bttnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSumaActionPerformed
        op='+';
        a=Double.parseDouble(txtValores.getText());
        txtValores.setText("");
        Numero="";
        txtValores.requestFocus();
    }//GEN-LAST:event_bttnSumaActionPerformed

    private void bttnNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero8ActionPerformed
        Numero=Numero+"8";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero8ActionPerformed

    private void bttnNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero9ActionPerformed
        Numero=Numero+"9";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero9ActionPerformed

    private void bttnNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero0ActionPerformed
        Numero=Numero+"0";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero0ActionPerformed

    private void bttnNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNumero7ActionPerformed
        Numero=Numero+"7";
        txtValores.setText(Numero);
    }//GEN-LAST:event_bttnNumero7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnClear;
    private javax.swing.JButton bttnDivision;
    private javax.swing.JButton bttnFactorial;
    private javax.swing.JButton bttnMultiplicacion;
    private javax.swing.JButton bttnNumero0;
    private javax.swing.JButton bttnNumero1;
    private javax.swing.JButton bttnNumero2;
    private javax.swing.JButton bttnNumero3;
    private javax.swing.JButton bttnNumero4;
    private javax.swing.JButton bttnNumero5;
    private javax.swing.JButton bttnNumero6;
    private javax.swing.JButton bttnNumero7;
    private javax.swing.JButton bttnNumero8;
    private javax.swing.JButton bttnNumero9;
    private javax.swing.JButton bttnPunto;
    private javax.swing.JButton bttnResta;
    private javax.swing.JButton bttnResultado;
    private javax.swing.JButton bttnSuma;
    private javax.swing.JTextField txtValores;
    // End of variables declaration//GEN-END:variables
}
