/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Cajas.Usuario;
import Clases.Fondo;
import java.awt.BorderLayout;


/**
 *
 * @author User
 */
public class VentanaPrincipal extends javax.swing.JFrame {
String us;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
         setLocationRelativeTo(null);
         us = Usuario.Ingresar("Ingrese un nombre de usuario : ");
         lblUsuario.setText(us);
        Fondo p = new Fondo("Fondo.png"); 
        this.add( p , BorderLayout.CENTER); 
        p.repaint();
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgenda = new javax.swing.JLabel();
        lblCalculadora = new javax.swing.JLabel();
        lblJuego = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escritorio");

        lblAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen2_2.png"))); // NOI18N
        lblAgenda.setText("Agenda");
        lblAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAgenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAgendaMousePressed(evt);
            }
        });

        lblCalculadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen2.png"))); // NOI18N
        lblCalculadora.setText("Calculadora");
        lblCalculadora.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblCalculadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCalculadora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalculadoraMouseClicked(evt);
            }
        });

        lblJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen3.png"))); // NOI18N
        lblJuego.setText("Juego");
        lblJuego.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblJuego.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJuegoMouseClicked(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Miriam Fixed", 1, 11)); // NOI18N
        lblUsuario.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCalculadora)
                    .addComponent(lblJuego))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJuego))
                .addGap(70, 70, 70)
                .addComponent(lblCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(lblUsuario))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJuegoMouseClicked
        new Juego().setVisible(true);
    }//GEN-LAST:event_lblJuegoMouseClicked

    private void lblCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalculadoraMouseClicked
        new Calculadora().setVisible(true);
    }//GEN-LAST:event_lblCalculadoraMouseClicked

    private void lblAgendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendaMousePressed
        new Agenda().setVisible(true);
    }//GEN-LAST:event_lblAgendaMousePressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JLabel lblJuego;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
